# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/my_test_database?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=rU^c*sM_SL1.ye
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.example=DEBUG